import streamlit as st
from parser.grammar_parser import parse_grammar, GrammarError
from parser.earley_parser import parse_input
from analysis.ambiguity import analyze_trees, diagnose_ambiguity
from visualization.tree_visualizer import render_tree

st.set_page_config(
    page_title="CFG Ambiguity Analyzer",
    page_icon="🌳",
    layout="wide"
)

st.title("🌳 CFG Ambiguity Analyzer")
st.caption("Visualize parse trees, detect sentence ambiguity, and inspect structural differences.")

DEFAULT_GRAMMAR = """E -> E + E
E -> E * E
E -> ( E )
E -> id"""

DEFAULT_INPUT = "id + id * id"

with st.sidebar:
    st.header("Settings")
    max_trees = st.slider(
        "Maximum parse trees",
        min_value=2,
        max_value=50,
        value=10,
        help="Parsing stops after this many distinct trees are collected."
    )
    st.markdown("---")
    st.markdown(
        "**Important:** This application analyzes the supplied input sentence. "
        "It does not claim to mathematically decide ambiguity of every possible "
        "sentence in an arbitrary CFG."
    )

col1, col2 = st.columns(2)

with col1:
    grammar_text = st.text_area(
        "Context-Free Grammar",
        value=DEFAULT_GRAMMAR,
        height=250,
        help="Use one production per line. Example: E -> E + E | id"
    )

with col2:
    input_text = st.text_input(
        "Input sentence",
        value=DEFAULT_INPUT,
        help="Separate tokens with spaces."
    )

analyze = st.button("🔎 Analyze Grammar", type="primary", use_container_width=True)

if analyze:
    try:
        grammar = parse_grammar(grammar_text)
    except GrammarError as exc:
        st.error(f"Grammar error: {exc}")
        st.stop()

    if not grammar.start_symbol:
        st.error("No grammar productions were found.")
        st.stop()

    with st.spinner("Parsing input and generating parse trees..."):
        result = parse_input(
            grammar,
            input_text,
            max_trees=max_trees
        )

    if not result.accepted:
        st.error("❌ Input is NOT generated by this grammar.")
        st.info(
            "Try checking the grammar rules, token spacing, or the input sentence."
        )
        if result.message:
            st.code(result.message)
        st.stop()

    report = analyze_trees(result.trees, truncated=result.truncated)

    if report["ambiguous"]:
        st.error("🔴 AMBIGUOUS")
        st.write(
            f"At least **{report['tree_count']} distinct parse trees** "
            "were found for the supplied sentence."
        )
    else:
        st.success("🟢 UNAMBIGUOUS FOR THIS INPUT")
        st.write("Exactly one parse tree was found.")

    if result.truncated:
        st.warning(
            f"The search reached the configured limit of {max_trees} trees. "
            "The result is therefore bounded: more alternatives may exist."
        )

    m1, m2, m3 = st.columns(3)
    m1.metric("Input tokens", result.token_count)
    m2.metric("Parse trees", report["tree_count"])
    m3.metric("Grammar rules", grammar.rule_count)

    st.subheader("📋 Grammar")
    st.code(grammar.pretty())

    if report["ambiguous"]:
        st.subheader("🩺 Ambiguity Diagnosis")
        diagnosis = diagnose_ambiguity(result.trees)
        st.markdown(diagnosis["summary"])

        if diagnosis["differences"]:
            st.markdown("**Structural differences between alternatives:**")
            for diff in diagnosis["differences"]:
                st.write(f"• {diff}")

        if diagnosis["shared_root"]:
            st.info(f"Shared root symbol: `{diagnosis['shared_root']}`")

    st.subheader("🌳 Parse Tree Visualization")

    trees = result.trees
    tabs = st.tabs([f"Tree {i+1}" for i in range(len(trees))])

    for i, (tab, tree) in enumerate(zip(tabs, trees)):
        with tab:
            st.markdown(f"### Parse Tree {i+1}")
            fig = render_tree(tree)
            st.pyplot(fig, clear_figure=True, use_container_width=True)

            with st.expander("View tree structure"):
                st.code(tree.to_text())

    if len(trees) >= 2:
        st.subheader("⚖️ Compare Alternatives")
        left, right = st.columns(2)
        with left:
            st.markdown("**Parse Tree 1**")
            st.code(trees[0].to_text())
        with right:
            st.markdown("**Parse Tree 2**")
            st.code(trees[1].to_text())

st.markdown("---")
st.caption(
    "CFG Ambiguity Analyzer • Educational compiler/formal-language project"
)
